# Generated by Django 3.0.5 on 2021-05-24 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_close', models.BooleanField(default=False)),
                ('range_booking', models.DurationField()),
                ('payment_member_duration', models.DurationField()),
                ('payment_guest_duration', models.DurationField()),
                ('payment_group_duration', models.DurationField(null=True)),
                ('refund_member_duration', models.DurationField()),
                ('groupbooking_lastmonth_day', models.PositiveIntegerField(null=True)),
                ('refund_group_day', models.PositiveIntegerField(null=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('num_of_creategroup', models.PositiveIntegerField()),
                ('announce', models.CharField(max_length=1000)),
                ('contacts', models.CharField(max_length=500)),
                ('rules', models.CharField(max_length=1000)),
                ('fes_date_start', models.DateField(null=True)),
                ('fes_date_end', models.DateField(null=True)),
                ('payment_member_duration_fes', models.DurationField(null=True)),
                ('refund_member_duration_fes', models.DurationField(null=True)),
            ],
            options={
                'db_table': 'bcb_allcourtinfo',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('booking_datetime', models.DateTimeField()),
                ('exp_datetime', models.DateTimeField(null=True)),
                ('refund_datetime', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 5, 23, 19, 992649, tzinfo=utc))),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_state', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 5, 23, 19, 992649, tzinfo=utc))),
                ('bookingid', models.CharField(max_length=32, unique=True)),
                ('paymentid', models.CharField(max_length=32, null=True)),
                ('refundid', models.CharField(max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bcb_booking',
            },
        ),
        migrations.CreateModel(
            name='EachCourtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.IntegerField(unique=True)),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_mem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_group', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_ds_start', models.TimeField()),
                ('time_ds_end', models.TimeField()),
                ('is_maintain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bcb_eachcourtinfo',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=32, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 5, 23, 19, 992649, tzinfo=utc))),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_founded', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bcb_payment',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundid', models.CharField(max_length=32, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bank_acc_id', models.CharField(max_length=20)),
                ('bank_acc_name', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 5, 23, 19, 993648, tzinfo=utc))),
                ('is_refunded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bcb_refund',
            },
        ),
    ]
