# Generated by Django 3.0.5 on 2021-05-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AddField(
            model_name='refund',
            name='member',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='booking.EachCourtInfo'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
