# Generated by Django 3.0.5 on 2021-05-26 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210525_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='refund_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 55, 25, 672515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 55, 25, 672515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 55, 25, 681510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 55, 25, 682509, tzinfo=utc)),
        ),
    ]
