# Generated by Django 3.1 on 2021-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210526_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourtInfoMultiValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fes_date_start', models.DateField(null=True)),
                ('fes_date_end', models.DateField(null=True)),
                ('payment_member_duration_fes', models.DurationField(null=True)),
                ('refund_member_duration_fes', models.DurationField(null=True)),
            ],
            options={
                'db_table': 'bcb_allcourtinfo_multivalue',
            },
        ),
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='fes_date_end',
        ),
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='fes_date_start',
        ),
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='payment_member_duration_fes',
        ),
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='refund_member_duration_fes',
        ),
    ]
