# Generated by Django 3.1 on 2021-05-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210601_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fes_name', models.CharField(max_length=100)),
                ('fes_date_start', models.DateField(null=True)),
                ('fes_date_end', models.DateField(null=True)),
                ('payment_member_duration_fes', models.DurationField(null=True)),
                ('refund_member_duration_fes', models.DurationField(null=True)),
            ],
            options={
                'db_table': 'bcb_festivalinfo',
            },
        ),
        migrations.DeleteModel(
            name='AllCourtInfoMultiValue',
        ),
    ]
